"""
knowledge_base/ontology.py
==========================
Deliverable 4.2 — Ontology Design
4-Level Class Hierarchy | 20 Classes | 8 Object Properties | 6 Data Properties | 8 DL Axioms
"""

# ─────────────────────────────────────────────────────────────────────────────
# 4-LEVEL CLASS TAXONOMY  (20 named classes)
# ─────────────────────────────────────────────────────────────────────────────

CLASSES: dict[str, dict] = {
    # Level 1 — Root
    "Thing":                 {"level": 1, "parent": None,             "desc": "Root class for all ontology entities"},
    # Level 2 — Domain
    "Person":                {"level": 2, "parent": "Thing",          "desc": "Any human actor in the university"},
    "AcademicEntity":        {"level": 2, "parent": "Thing",          "desc": "Academic items such as courses and programs"},
    "Assessment":            {"level": 2, "parent": "Thing",          "desc": "Evaluation and grading structures"},
    "Advisory":              {"level": 2, "parent": "Thing",          "desc": "Decisions, recommendations, and outcomes"},
    # Level 3 — Sub-domain
    "Student":               {"level": 3, "parent": "Person",         "desc": "A student enrolled at the university"},
    "Advisor":               {"level": 3, "parent": "Person",         "desc": "An academic advisor assigned to students"},
    "Course":                {"level": 3, "parent": "AcademicEntity", "desc": "A university course with credits and prerequisites"},
    "Program":               {"level": 3, "parent": "AcademicEntity", "desc": "A degree program (e.g., BSc Computer Science)"},
    "Grade":                 {"level": 3, "parent": "Assessment",     "desc": "A grade received by a student in a course"},
    "Recommendation":        {"level": 3, "parent": "Advisory",       "desc": "A course or action recommended by the system"},
    "Alert":                 {"level": 3, "parent": "Advisory",       "desc": "A warning or escalation generated by the system"},
    # Level 4 — Leaf
    "UndergraduateStudent":  {"level": 4, "parent": "Student",        "desc": "A bachelor's-level student"},
    "GraduateStudent":       {"level": 4, "parent": "Student",        "desc": "A master's or PhD-level student"},
    "AtRiskStudent":         {"level": 4, "parent": "Student",        "desc": "A student with GPA < 2.0 in academic difficulty"},
    "HonorsStudent":         {"level": 4, "parent": "Student",        "desc": "High-achiever: GPA >= 3.7 and credits >= 60"},
    "CoreCourse":            {"level": 4, "parent": "Course",         "desc": "A mandatory course required for graduation"},
    "ElectiveCourse":        {"level": 4, "parent": "Course",         "desc": "An optional course chosen by the student"},
    "CapstoneProject":       {"level": 4, "parent": "Course",         "desc": "The final-year graduation project course"},
    "AcademicProbation":     {"level": 4, "parent": "Alert",          "desc": "Alert: student is on academic probation"},
    "GraduationClearance":   {"level": 4, "parent": "Advisory",       "desc": "System decision: student is cleared to graduate"},
}

# ─────────────────────────────────────────────────────────────────────────────
# OBJECT PROPERTIES  (8)
# ─────────────────────────────────────────────────────────────────────────────

OBJECT_PROPERTIES: dict[str, dict] = {
    "enrolledIn":          {"domain": "Student",  "range": "Course",  "desc": "Student is enrolled in a course"},
    "hasAdvisor":          {"domain": "Student",  "range": "Advisor", "desc": "Student has an assigned academic advisor"},
    "requiresPrerequisite":{"domain": "Course",   "range": "Course",  "desc": "Course A must be completed before Course B"},
    "belongsToProgram":    {"domain": "Course",   "range": "Program", "desc": "Course is part of a specific degree program"},
    "receivedGrade":       {"domain": "Student",  "range": "Grade",   "desc": "Student received a grade for a course"},
    "hasAlert":            {"domain": "Student",  "range": "Alert",   "desc": "Student has one or more academic alerts"},
    "systemRecommends":    {"domain": "Advisory", "range": "Course",  "desc": "System recommends a course to a student"},
    "completedCourse":     {"domain": "Student",  "range": "Course",  "desc": "Student successfully completed a course"},
}

# ─────────────────────────────────────────────────────────────────────────────
# DATA PROPERTIES  (6)
# ─────────────────────────────────────────────────────────────────────────────

DATA_PROPERTIES: dict[str, dict] = {
    "gpa":               {"domain": "Student", "range": "float",  "desc": "Cumulative GPA on a 0.0–4.0 scale"},
    "creditHours":       {"domain": "Course",  "range": "int",    "desc": "Credit hours assigned to a course"},
    "totalCredits":      {"domain": "Student", "range": "int",    "desc": "Total credit hours the student has earned"},
    "currentSemester":   {"domain": "Student", "range": "string", "desc": "Student's current academic semester"},
    "stressIndex":       {"domain": "Student", "range": "float",  "desc": "Computed workload stress 0.0 (none) – 1.0 (critical)"},
    "careerInterest":    {"domain": "Student", "range": "string", "desc": "Student's declared career domain"},
}

# ─────────────────────────────────────────────────────────────────────────────
# DESCRIPTION LOGIC AXIOMS  (8)
# ─────────────────────────────────────────────────────────────────────────────

DL_AXIOMS: list[tuple[str, str, str]] = [
    ("Subsumption",
     "Student ⊑ Person",
     "Every Student is necessarily a Person."),

    ("Subsumption",
     "AtRiskStudent ⊑ UndergraduateStudent ⊓ ∃hasGPA.(<2.0)",
     "An AtRiskStudent is an UndergraduateStudent with GPA < 2.0."),

    ("Equivalence",
     "HonorsStudent ≡ Student ⊓ ∃hasGPA.(≥3.7) ⊓ ∃totalCredits.(≥60)",
     "A HonorsStudent is EXACTLY a Student with GPA >= 3.7 AND credits >= 60."),

    ("Disjointness",
     "UndergraduateStudent ⊓ GraduateStudent ⊑ ⊥",
     "A student cannot simultaneously be Undergraduate and Graduate."),

    ("Disjointness",
     "CoreCourse ⊓ ElectiveCourse ⊑ ⊥",
     "A course cannot be both Core and Elective at the same time."),

    ("Subsumption",
     "∃hasAlert.AcademicProbation ⊑ AtRiskStudent",
     "Any student with an AcademicProbation alert is necessarily an AtRiskStudent."),

    ("Equivalence",
     "GraduationClearance ≡ ∀completedCourse.(CoreCourse) ⊓ ∃hasGPA.(≥2.0)",
     "GraduationClearance is granted EXACTLY when all core courses are done AND GPA >= 2.0."),

    ("Subsumption",
     "∃enrolledIn.CapstoneProject ⊑ ∃totalCredits.(≥90)",
     "Any student enrolled in a CapstoneProject must have earned at least 90 credits."),
]